version: '3'

networks:
  overlay:

volumes:
  pg_data:
    driver: local

services:
  postgres:
    image: binakot/postgresql-postgis-timescaledb:latest
    container_name: KZ_POSTGRESQL_POSTGIS
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kizora@123
    ports:
      - 5433:5432
    networks:
      - overlay
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: KZ_PGADMIN_POSTGIS
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@kizora.com
      - PGADMIN_DEFAULT_PASSWORD=Kizora@123
    ports:
      - 8080:80
    networks:
      - overlay
